const fs = require('fs');
let c = fs.readFileSync('C:/Users/jcafp/.openclaw/workspace/mundial-streams/index.html', 'utf8');

const search = "  // Streams\n  html += '<div class=\"streams\">';\n  if (str && str.length) {\n    str.forEach(function(st) {\n      var cls = st.type === \"official\" ? \"official\" : \"alternative\";\n      html += '<a class=\"stream-btn ' + cls + '\" href=\"' + st.url + '\" target=\"_blank\" rel=\"noopener\">' + (st.type===\"official\"?\"\\u25B6\":\"\\u2387\") + ' ' + st.name + '</a>';\n    });\n  } else {\n    var hI = bcast(m.home_team_name_en);\n    var aI = bcast(m.away_team_name_en);\n    var off = (hI?.official||[]).concat(aI?.official||[]);\n    var alt = (hI?.alternative||[]).concat(aI?.alternative||[]);\n    if (off.length||alt.length) {\n      var seen = {};\n      (off.concat(alt)).forEach(function(st) {\n        if (seen[st.name]) return; seen[st.name] = true;\n        var cls = off.indexOf(st) >= 0 ? \"official\" : \"alternative\";\n        html += '<a class=\"stream-btn ' + cls + '\" href=\"' + st.url + '\" target=\"_blank\" rel=\"noopener\">' + (off.indexOf(st)>=0?\"\\u25B6\":\"\\u2387\") + ' ' + st.name + '</a>';\n      });\n    } else {\n      var q = encodeURIComponent(m.home_team_name_en + \" vs \" + m.away_team_name_en + \" World Cup 2026\");\n      if (live) {\n        html += '<a class=\"stream-btn no-stream\" href=\"https://www.google.com/search?q=' + q + '+live+stream\" target=\"_blank\" rel=\"noopener\">\\uD83D\\uDD0D Google</a>';\n        html += '<a class=\"stream-btn no-stream\" href=\"https://www.youtube.com/results?search_query=' + q + '+live\" target=\"_blank\" rel=\"noopener\">\\u25B6 YouTube</a>';\n        html += '<a class=\"stream-btn no-stream\" href=\"https://old.reddit.com/r/soccerstreams/search?q=' + q + '&restrict_sr=on&sort=new\" target=\"_blank\" rel=\"noopener\">\\uD83D\\uDC7D Reddit</a>';\n      } else {\n        html += '<a class=\"stream-btn no-stream\" href=\"https://www.google.com/search?q=' + q + '+transmision\" target=\"_blank\" rel=\"noopener\">\\uD83D\\uDD0D buscar transmisi\\u00F3n</a>';\n      }\n    }\n  }\n  html += '</div></div>';";

const replace = "  // Streams\n  html += '<div class=\"streams\">';\n  if (str && str.length) {\n    str.forEach(function(st) {\n      var cls = st.type === \"official\" ? \"official\" : \"alternative\";\n      html += '<a class=\"stream-btn ' + cls + '\" href=\"' + st.url + '\" target=\"_blank\" rel=\"noopener\">' + (st.type===\"official\"?\"\\u25B6\":\"\\u2387\") + ' ' + st.name + '</a>';\n    });\n  } else {\n    var hI = bcast(m.home_team_name_en);\n    var aI = bcast(m.away_team_name_en);\n    var off = (hI?.official||[]).concat(aI?.official||[]);\n    var alt = (hI?.alternative||[]).concat(aI?.alternative||[]);\n    if (off.length||alt.length) {\n      var seen = {};\n      (off.concat(alt)).forEach(function(st) {\n        if (seen[st.name]) return; seen[st.name] = true;\n        var cls = off.indexOf(st) >= 0 ? \"official\" : \"alternative\";\n        html += '<a class=\"stream-btn ' + cls + '\" href=\"' + st.url + '\" target=\"_blank\" rel=\"noopener\">' + (off.indexOf(st)>=0?\"\\u25B6\":\"\\u2387\") + ' ' + st.name + '</a>';\n      });\n    } else if (live) {\n      var q = encodeURIComponent(m.home_team_name_en + ' vs ' + m.away_team_name_en + ' 2026');\n      html += '<a class=\"stream-btn alternative\" href=\"https://rojadirectamas.fi/\" target=\"_blank\" rel=\"noopener\">\\u26BD Rojadirecta</a>';\n      html += '<a class=\"stream-btn alternative\" href=\"https://www.youtube.com/results?search_query=' + q + '+live\" target=\"_blank\" rel=\"noopener\">\\u25B6 YouTube</a>';\n      html += '<a class=\"stream-btn alternative\" href=\"https://old.reddit.com/r/soccerstreams/search?q=' + q + '&restrict_sr=on&sort=new\" target=\"_blank\" rel=\"noopener\">\\uD83D\\uDC7D Reddit</a>';\n    } else {\n      html += '<span class=\"stream-btn no-stream\">\\u2014 sin stream \\u2014</span>';\n    }\n  }\n  html += '</div></div>';";

if (c.includes(search)) {
  c = c.replace(search, replace);
  fs.writeFileSync('C:/Users/jcafp/.openclaw/workspace/mundial-streams/index.html', c, 'utf8');
  console.log('REPLACED');
} else {
  console.log('NOT FOUND');
}
