const fs = require('fs');
let c = fs.readFileSync('C:/Users/jcafp/.openclaw/workspace/mundial-streams/index.html', 'utf8');

const search = "function renderGroups(el) {\n  if (!allGroups.length) {\n    el.innerHTML = '<div class=\"loading\">\\u2014 no group data \\u2014</div>';\n    return;\n  }\n  var html = '<div class=\"groups-view\">';\n  allGroups.forEach(function(grp) {\n    html += '<div class=\"group-card\">' +\n      '<div class=\"group-title\">GROUP ' + grp.name + '<span class=\"bar\"></span></div>' +\n      '<table class=\"group-table\"><tr>' +\n        '<th style=\"text-align:left;padding-left:0.7rem\">#</th>' +\n        '<th style=\"text-align:left\">Team</th>' +\n        '<th>P</th><th>W</th><th>D</th><th>L</th>' +\n        '<th>GF</th><th>GA</th><th>GD</th><th style=\"padding-right:0.7rem\">Pts</th>' +\n      '</tr>';\n    // Sort by pts desc, then GD desc\n    var sorted = (grp.teams || []).slice().sort(function(a, b) {\n      if (+b.pts !== +a.pts) return +b.pts - +a.pts;\n      return +b.gd - +a.gd;\n    });\n    sorted.forEach(function(t, i) {\n      var nm = teamName(t.team_id);\n      var fl = teamFlag(t.team_id);\n      var gd = +t.gd;\n      var gdCls = gd > 0 ? \"gd-pos\" : gd < 0 ? \"gd-neg\" : \"\";\n      var hl = t.pts >= 4 ? \"highlight\" : \"\";\n      html += '<tr class=\"' + hl + '\">' +\n        '<td style=\"padding-left:0.7rem\"><span class=\"pos\">' + (i + 1) + '</span></td>' +\n        '<td style=\"text-align:left\"><span class=\"flag\">' + fl + '</span> ' + nm + '</td>' +\n        '<td>' + t.mp + '</td>' +\n        '<td>' + t.w + '</td>' +\n        '<td>' + t.d + '</td>' +\n        '<td>' + t.l + '</td>' +\n        '<td>' + t.gf + '</td>' +\n        '<td>' + t.ga + '</td>' +\n        '<td class=\"' + gdCls + '\">' + (gd > 0 ? \"+\" : \"\") + gd + '</td>' +\n        '<td class=\"pts\" style=\"padding-right:0.7rem\">' + t.pts + '</td>' +\n      '</tr>';\n    });\n    html += '</table></div>';\n  });\n  html += '</div>';\n  el.innerHTML = html;\n}";

const replace = "function renderGroups(el) {\n  if (!allGroups.length) {\n    el.innerHTML = '<div class=\"loading\">\\u2014 no group data \\u2014</div>';\n    return;\n  }\n  var html = '<div class=\"groups-view\">';\n  allGroups.forEach(function(grp) {\n    html += '<div class=\"group-card\">' +\n      '<div class=\"group-title\">GRUPO ' + grp.name + '<span class=\"bar\"></span></div>' +\n      '<table class=\"group-table\"><tr>' +\n        '<th>#</th>' +\n        '<th style=\"text-align:left\">Equipo</th>' +\n        '<th>PJ</th><th>G</th><th>E</th><th>P</th>' +\n        '<th>GF</th><th>GC</th><th>DG</th><th style=\"padding-right:0.8rem\">Pts</th>' +\n      '</tr>';\n    var sorted = (grp.teams || []).slice().sort(function(a, b) {\n      if (+b.pts !== +a.pts) return +b.pts - +a.pts;\n      return +b.gd - +a.gd;\n    });\n    sorted.forEach(function(t, i) {\n      var nm = teamName(t.team_id);\n      var fl = teamFlag(t.team_id);\n      var gd = +t.gd;\n      var gdCls = gd > 0 ? \"gd-pos\" : gd < 0 ? \"gd-neg\" : \"\";\n      var stripe = i % 2 === 1 ? ' stripe' : '';\n      var posCls = 'pos';\n      if (i === 0) posCls += ' leader';\n      else if (i < 3) posCls += ' top3';\n      html += '<tr class=\"' + stripe + '\">' +\n        '<td><span class=\"' + posCls + '\">' + (i + 1) + '</span></td>' +\n        '<td style=\"text-align:left;padding-left:0.3rem\"><span class=\"flag\">' + fl + '</span> ' + nm + '</td>' +\n        '<td>' + t.mp + '</td>' +\n        '<td>' + t.w + '</td>' +\n        '<td>' + t.d + '</td>' +\n        '<td>' + t.l + '</td>' +\n        '<td>' + t.gf + '</td>' +\n        '<td>' + t.ga + '</td>' +\n        '<td class=\"' + gdCls + '\">' + (gd > 0 ? \"+\" : \"\") + gd + '</td>' +\n        '<td class=\"pts\">' + t.pts + '</td>' +\n      '</tr>';\n    });\n    html += '</table></div>';\n  });\n  html += '</div>';\n  el.innerHTML = html;\n}";

if (c.includes(search)) {
  c = c.replace(search, replace);
  fs.writeFileSync('C:/Users/jcafp/.openclaw/workspace/mundial-streams/index.html', c, 'utf8');
  console.log('REPLACED');
} else {
  console.log('NOT FOUND - checking renderGroups...');
  var idx = c.indexOf('function renderGroups');
  if (idx >= 0) console.log('Found at', idx, '- showing 500 chars:', c.substring(idx, idx+500));
}
